#************************Makefile***************************
#Program: RouteStandard4m
#Compiler: GCC
#Author: Jesimar da Silva Arantes
#Date: 08/06/2016
#Last Update: 21/09/2018
#Description: Program to generate route with standard format for the UAV.
#Descrição: Programa para gerar rota com formato padrão para o VANT.
#***********************************************************

all: RouteStandard4m

uav_routes_standard: RouteStandard4m.c
	gcc RouteStandard4m.c -o RouteStandard4m -lm

clean:
	rm -rf *.o RouteStandard4m
