// Generated by gencpp from file drone_system/AddTwoInts.msg
// DO NOT EDIT!


#ifndef DRONE_SYSTEM_MESSAGE_ADDTWOINTS_H
#define DRONE_SYSTEM_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <drone_system/AddTwoIntsRequest.h>
#include <drone_system/AddTwoIntsResponse.h>


namespace drone_system
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace drone_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_system::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::drone_system::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::drone_system::AddTwoInts > {
  static const char* value()
  {
    return "drone_system/AddTwoInts";
  }

  static const char* value(const ::drone_system::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::drone_system::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::drone_system::AddTwoInts > 
template<>
struct MD5Sum< ::drone_system::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_system::AddTwoInts >::value();
  }
  static const char* value(const ::drone_system::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_system::AddTwoIntsRequest> should match 
// service_traits::DataType< ::drone_system::AddTwoInts > 
template<>
struct DataType< ::drone_system::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::drone_system::AddTwoInts >::value();
  }
  static const char* value(const ::drone_system::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_system::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::drone_system::AddTwoInts > 
template<>
struct MD5Sum< ::drone_system::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_system::AddTwoInts >::value();
  }
  static const char* value(const ::drone_system::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_system::AddTwoIntsResponse> should match 
// service_traits::DataType< ::drone_system::AddTwoInts > 
template<>
struct DataType< ::drone_system::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::drone_system::AddTwoInts >::value();
  }
  static const char* value(const ::drone_system::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_SYSTEM_MESSAGE_ADDTWOINTS_H
