// Generated by gencpp from file drone_system/path_msgRequest.msg
// DO NOT EDIT!


#ifndef DRONE_SYSTEM_MESSAGE_PATH_MSGREQUEST_H
#define DRONE_SYSTEM_MESSAGE_PATH_MSGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace drone_system
{
template <class ContainerAllocator>
struct path_msgRequest_
{
  typedef path_msgRequest_<ContainerAllocator> Type;

  path_msgRequest_()
    : option()  {
    }
  path_msgRequest_(const ContainerAllocator& _alloc)
    : option(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _option_type;
  _option_type option;





  typedef boost::shared_ptr< ::drone_system::path_msgRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::drone_system::path_msgRequest_<ContainerAllocator> const> ConstPtr;

}; // struct path_msgRequest_

typedef ::drone_system::path_msgRequest_<std::allocator<void> > path_msgRequest;

typedef boost::shared_ptr< ::drone_system::path_msgRequest > path_msgRequestPtr;
typedef boost::shared_ptr< ::drone_system::path_msgRequest const> path_msgRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::drone_system::path_msgRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::drone_system::path_msgRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace drone_system

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/kinetic/share/geographic_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/kinetic/share/uuid_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/kinetic/share/mavros_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::drone_system::path_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::drone_system::path_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_system::path_msgRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::drone_system::path_msgRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_system::path_msgRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::drone_system::path_msgRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::drone_system::path_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7be597108526c007715ebf9a51b492e9";
  }

  static const char* value(const ::drone_system::path_msgRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7be597108526c007ULL;
  static const uint64_t static_value2 = 0x715ebf9a51b492e9ULL;
};

template<class ContainerAllocator>
struct DataType< ::drone_system::path_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "drone_system/path_msgRequest";
  }

  static const char* value(const ::drone_system::path_msgRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::drone_system::path_msgRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string option\n\
";
  }

  static const char* value(const ::drone_system::path_msgRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::drone_system::path_msgRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.option);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct path_msgRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::drone_system::path_msgRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::drone_system::path_msgRequest_<ContainerAllocator>& v)
  {
    s << indent << "option: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.option);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DRONE_SYSTEM_MESSAGE_PATH_MSGREQUEST_H
