// Generated by gencpp from file drone_system/path_msg.msg
// DO NOT EDIT!


#ifndef DRONE_SYSTEM_MESSAGE_PATH_MSG_H
#define DRONE_SYSTEM_MESSAGE_PATH_MSG_H

#include <ros/service_traits.h>


#include <drone_system/path_msgRequest.h>
#include <drone_system/path_msgResponse.h>


namespace drone_system
{

struct path_msg
{

typedef path_msgRequest Request;
typedef path_msgResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct path_msg
} // namespace drone_system


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::drone_system::path_msg > {
  static const char* value()
  {
    return "c48136865ebee6f8ec8dec3519522f22";
  }

  static const char* value(const ::drone_system::path_msg&) { return value(); }
};

template<>
struct DataType< ::drone_system::path_msg > {
  static const char* value()
  {
    return "drone_system/path_msg";
  }

  static const char* value(const ::drone_system::path_msg&) { return value(); }
};


// service_traits::MD5Sum< ::drone_system::path_msgRequest> should match 
// service_traits::MD5Sum< ::drone_system::path_msg > 
template<>
struct MD5Sum< ::drone_system::path_msgRequest>
{
  static const char* value()
  {
    return MD5Sum< ::drone_system::path_msg >::value();
  }
  static const char* value(const ::drone_system::path_msgRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_system::path_msgRequest> should match 
// service_traits::DataType< ::drone_system::path_msg > 
template<>
struct DataType< ::drone_system::path_msgRequest>
{
  static const char* value()
  {
    return DataType< ::drone_system::path_msg >::value();
  }
  static const char* value(const ::drone_system::path_msgRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::drone_system::path_msgResponse> should match 
// service_traits::MD5Sum< ::drone_system::path_msg > 
template<>
struct MD5Sum< ::drone_system::path_msgResponse>
{
  static const char* value()
  {
    return MD5Sum< ::drone_system::path_msg >::value();
  }
  static const char* value(const ::drone_system::path_msgResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::drone_system::path_msgResponse> should match 
// service_traits::DataType< ::drone_system::path_msg > 
template<>
struct DataType< ::drone_system::path_msgResponse>
{
  static const char* value()
  {
    return DataType< ::drone_system::path_msg >::value();
  }
  static const char* value(const ::drone_system::path_msgResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DRONE_SYSTEM_MESSAGE_PATH_MSG_H
