// Generated by gencpp from file planners/GA_PlannerResponse.msg
// DO NOT EDIT!


#ifndef PLANNERS_MESSAGE_GA_PLANNERRESPONSE_H
#define PLANNERS_MESSAGE_GA_PLANNERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace planners
{
template <class ContainerAllocator>
struct GA_PlannerResponse_
{
  typedef GA_PlannerResponse_<ContainerAllocator> Type;

  GA_PlannerResponse_()
    : wp_path()  {
    }
  GA_PlannerResponse_(const ContainerAllocator& _alloc)
    : wp_path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _wp_path_type;
  _wp_path_type wp_path;





  typedef boost::shared_ptr< ::planners::GA_PlannerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::planners::GA_PlannerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GA_PlannerResponse_

typedef ::planners::GA_PlannerResponse_<std::allocator<void> > GA_PlannerResponse;

typedef boost::shared_ptr< ::planners::GA_PlannerResponse > GA_PlannerResponsePtr;
typedef boost::shared_ptr< ::planners::GA_PlannerResponse const> GA_PlannerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::planners::GA_PlannerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::planners::GA_PlannerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace planners

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geographic_msgs': ['/opt/ros/melodic/share/geographic_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'mavros_msgs': ['/opt/ros/melodic/share/mavros_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg'], 'uuid_msgs': ['/opt/ros/melodic/share/uuid_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::planners::GA_PlannerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::planners::GA_PlannerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planners::GA_PlannerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::planners::GA_PlannerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planners::GA_PlannerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::planners::GA_PlannerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::planners::GA_PlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ada448ae45e59df26b471029dda5c76";
  }

  static const char* value(const ::planners::GA_PlannerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ada448ae45e59dfULL;
  static const uint64_t static_value2 = 0x26b471029dda5c76ULL;
};

template<class ContainerAllocator>
struct DataType< ::planners::GA_PlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "planners/GA_PlannerResponse";
  }

  static const char* value(const ::planners::GA_PlannerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::planners::GA_PlannerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string wp_path\n"
"\n"
;
  }

  static const char* value(const ::planners::GA_PlannerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::planners::GA_PlannerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.wp_path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GA_PlannerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::planners::GA_PlannerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::planners::GA_PlannerResponse_<ContainerAllocator>& v)
  {
    s << indent << "wp_path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.wp_path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLANNERS_MESSAGE_GA_PLANNERRESPONSE_H
