// Generated by gencpp from file planners/JarPlanners.msg
// DO NOT EDIT!


#ifndef PLANNERS_MESSAGE_JARPLANNERS_H
#define PLANNERS_MESSAGE_JARPLANNERS_H

#include <ros/service_traits.h>


#include <planners/JarPlannersRequest.h>
#include <planners/JarPlannersResponse.h>


namespace planners
{

struct JarPlanners
{

typedef JarPlannersRequest Request;
typedef JarPlannersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct JarPlanners
} // namespace planners


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::planners::JarPlanners > {
  static const char* value()
  {
    return "4227327d0bce5bc51aba1221199a837b";
  }

  static const char* value(const ::planners::JarPlanners&) { return value(); }
};

template<>
struct DataType< ::planners::JarPlanners > {
  static const char* value()
  {
    return "planners/JarPlanners";
  }

  static const char* value(const ::planners::JarPlanners&) { return value(); }
};


// service_traits::MD5Sum< ::planners::JarPlannersRequest> should match 
// service_traits::MD5Sum< ::planners::JarPlanners > 
template<>
struct MD5Sum< ::planners::JarPlannersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::planners::JarPlanners >::value();
  }
  static const char* value(const ::planners::JarPlannersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::planners::JarPlannersRequest> should match 
// service_traits::DataType< ::planners::JarPlanners > 
template<>
struct DataType< ::planners::JarPlannersRequest>
{
  static const char* value()
  {
    return DataType< ::planners::JarPlanners >::value();
  }
  static const char* value(const ::planners::JarPlannersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::planners::JarPlannersResponse> should match 
// service_traits::MD5Sum< ::planners::JarPlanners > 
template<>
struct MD5Sum< ::planners::JarPlannersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::planners::JarPlanners >::value();
  }
  static const char* value(const ::planners::JarPlannersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::planners::JarPlannersResponse> should match 
// service_traits::DataType< ::planners::JarPlanners > 
template<>
struct DataType< ::planners::JarPlannersResponse>
{
  static const char* value()
  {
    return DataType< ::planners::JarPlanners >::value();
  }
  static const char* value(const ::planners::JarPlannersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLANNERS_MESSAGE_JARPLANNERS_H
